---
- hosts: all
  remote_user: root
  tasks:

    - name: "Zabbix-agent"
      command: rpm -Uvh https://repo.zabbix.com/zabbix/4.1/rhel/7/x86_64/zabbix-release-4.1-1.el7.noarch.rpm 
      
    - name: "Update"
      command: yum update -y

    - name: "Install Packages"
      yum: name={{ item }} state=present
      with_items:
        - epel-release
        - vim
        - curl
        - wget
        - unzip
        - mlocate
        - zabbix-agent

    - name: "Install firewall"
      yum: name={{ item }} state=present
      with_items:
        - firewalld

    - name: "Turn on Firewalld and set them to run on boot"
      service: name={{ item }} state=started enabled=yes
      with_items:
        - firewalld

    - name: "Open port"
      command: firewall-cmd --permanent --add-port=22/tcp --add-port=10050/tcp --add-port=10051/tcp --add-port=3000/tcp --add-port=80/tcp --add-port=443/tcp --add-port=25/tcp --add-port=9150/tcp

    - name: "Restart"
      command: firewall-cmd --reload

    - name: "Turn on Zabbix-agent and set them to run on boot"
      service: name={{ item }} state=started enabled=yes
      with_items:
        - zabbix-agent  

- hosts: monitoring
  remote_user: root
  tasks:
    - name: "Install Docker"
      yum: name={{ item }} state=present
      with_items:
        - docker

    - name: "Turn on Docker and set them to run on boot"
      service: name={{ item }} state=started enabled=yes
      with_items:
        - docker

    - name: "Copy scripts"
      copy: src=/root/docker.sh dest=/root/

    - name: "Rules for scripts"
      command: chmod +x docker.sh

    - name: "Run scripts"
      command: ./docker.sh

    - name: "Delete scripts"
      command: rm -rf docker.sh

- hosts: api
  remote_user: root
  tasks:
    - name: "terraform"
      command: mkdir /root/terraform
    
    - name: "cd terraform"
      command: cd /root/terraform
    
    - name: "Download terraform"
      command: wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip

    - name: "unzip terraform"
      command: unzip terraform_0.11.11_linux_amd64.zip

    - name: "Delete"
      command: rm terraform_0.11.11_linux_amd64.zip