---
    - name: Add http Repository
      copy: src=/etc/yum.repos.d/ dest=/etc/yum.repos.d/ owner=root group=root
      register: repos

    - name: Install httpd
      yum: pkg=httpd state=latest
      when: repos|success
      register: httpdstalled
      notify:
          - httpd start

    - name: Status httpd
      yum: pkg=httpd state=latest
      register: httpdstalled
#      notify:
#          - httpd status
