---
    - name: Add Firewall Repository
      copy: src=/etc/yum.repos.d/ dest=/etc/yum.repos.d/ owner=root group=root
      register: repos

    - name: Install Firewall
      yum: pkg=firewalld state=latest
      when: repos|success
      register: firewalldinstalled
      notify:
          - firewalld start

